package scene

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"testing"

	"github.com/zostay/scifi-landscape/internal/canvas"
)

// groundTestContext builds the minimal Context a Ground generator/renderer needs
// for a seed: the ground random stream, the settings, and the shared ground
// gradient/variable flag. It mirrors how Scene.Build wires these up — in
// particular it rolls groundVariable on its own derived stream before building the
// ground gradient, exactly as Build does, so both generation and rendering see the
// identical shared globals (the gradient is a scene-wide global, not generated by
// the element).
func groundTestContext(seed int64, w, h int) *Context {
	settings := NewSettings(seed, "", h)
	gg := deriveRng(seed, "ground-gradient")
	variable := gg.Float64() < groundVariableChance
	return &Context{
		Ctx:            WithInstant(context.Background()),
		Canvas:         canvas.New(w, h),
		Settings:       settings,
		Seed:           seed,
		W:              w,
		H:              h,
		GroundGradient: buildGroundGradient(gg, settings.Time, variable),
		GroundVariable: variable,
		Rng:            deriveRng(seed, "ground"),
	}
}

// groundRenderListHash renders a ground scene list onto a fresh canvas and hashes
// the pixels. RenderList consumes no randomness, so the stream in the context is
// irrelevant here.
func groundRenderListHash(t *testing.T, seed int64, w, h int, list SceneList) string {
	t.Helper()
	c := groundTestContext(seed, w, h)
	if err := (&Ground{}).RenderList(c, list); err != nil {
		t.Fatalf("seed %d: render list: %v", seed, err)
	}
	buf := make([]byte, w*h*4)
	c.Canvas.Snapshot(buf)
	sum := sha256.Sum256(buf)
	return hex.EncodeToString(sum[:])
}

// TestGroundSceneListRoundTrip mirrors TestPlanetsSceneListRoundTrip: a generated
// ground scene list, serialized to YAML and read back, must (a) re-serialize to
// the same bytes and (b) render to the same pixels. This proves the "config +
// scene-list → render" reproducibility path for the base terrain.
func TestGroundSceneListRoundTrip(t *testing.T) {
	const w, h = 480, 270
	seeds := []int64{42, 7, 256, 3, 100, 1024, 31337, 11, 2, 5, 8, 13}
	var sawNonEmpty, sawVariable, sawNormal bool

	for _, seed := range seeds {
		gen := groundTestContext(seed, w, h)
		list, err := (&Ground{}).Generate(gen)
		if err != nil {
			t.Fatalf("seed %d: generate: %v", seed, err)
		}

		data, err := MarshalSceneList(list)
		if err != nil {
			t.Fatalf("seed %d: marshal: %v", seed, err)
		}
		got, err := UnmarshalSceneList(data)
		if err != nil {
			t.Fatalf("seed %d: unmarshal: %v", seed, err)
		}
		data2, err := MarshalSceneList(got)
		if err != nil {
			t.Fatalf("seed %d: re-marshal: %v", seed, err)
		}
		if !bytes.Equal(data, data2) {
			t.Errorf("seed %d: scene list not stable across YAML round-trip\n--- first ---\n%s\n--- second ---\n%s", seed, data, data2)
		}

		// The reconstructed list must render identically to the original.
		if a, b := groundRenderListHash(t, seed, w, h, list), groundRenderListHash(t, seed, w, h, got); a != b {
			t.Errorf("seed %d: round-tripped scene list renders differently:\n got  %s\n want %s", seed, b, a)
		}

		for _, e := range list {
			sawNonEmpty = true
			v, ok := e.(*GroundV0)
			if !ok {
				t.Fatalf("seed %d: unexpected entity type %T", seed, e)
			}
			if v.Variable {
				sawVariable = true
			} else {
				sawNormal = true
			}
		}
	}

	// Coverage sanity: the chosen seeds should produce a ground entity, and ideally
	// exercise both the normal and variable color modes, so the round-trip actually
	// covers both rng paths (the variable path draws the extra wander seed).
	if !sawNonEmpty {
		t.Fatal("no ground generated across all seeds; pick seeds with room below the horizon")
	}
	if !sawVariable {
		t.Log("note: no variable-mode ground in the seed set (wander-seed path not exercised)")
	}
	if !sawNormal {
		t.Log("note: no normal-mode ground in the seed set")
	}
}
