package scene

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"testing"

	"github.com/zostay/scifi-landscape/internal/canvas"
)

// skyTestContext builds the minimal Context a Sky generator/renderer needs for a
// seed: the settings, and the shared sky gradient (which RenderList samples for
// every row). It mirrors how Scene.Build wires these up — in particular it builds
// the sky gradient on its own derived stream, exactly as Build does, so both
// generation and rendering see the identical shared global (the gradient is a
// scene-wide global, not generated by the element). The sky element itself draws
// no randomness, so there is no element stream to wire here (Rng is left nil).
func skyTestContext(seed int64, w, h int) *Context {
	settings := NewSettings(seed, "", h)
	return &Context{
		Ctx:         WithInstant(context.Background()),
		Canvas:      canvas.New(w, h),
		Settings:    settings,
		Seed:        seed,
		W:           w,
		H:           h,
		SkyGradient: buildSkyGradient(deriveRng(seed, "sky-gradient"), settings.Time),
	}
}

// skyRenderListHash renders a sky scene list onto a fresh canvas and hashes the
// pixels. RenderList consumes no randomness, so the (absent) stream in the
// context is irrelevant here.
func skyRenderListHash(t *testing.T, seed int64, w, h int, list SceneList) string {
	t.Helper()
	c := skyTestContext(seed, w, h)
	if err := (&Sky{}).RenderList(c, list); err != nil {
		t.Fatalf("seed %d: render list: %v", seed, err)
	}
	buf := make([]byte, w*h*4)
	c.Canvas.Snapshot(buf)
	sum := sha256.Sum256(buf)
	return hex.EncodeToString(sum[:])
}

// TestSkySceneListRoundTrip mirrors TestPlanetsSceneListRoundTrip: a generated
// sky scene list, serialized to YAML and read back, must (a) re-serialize to the
// same bytes and (b) render to the same pixels. This proves the "config +
// scene-list → render" reproducibility path for the base sky. The sky consumes no
// randomness of its own — its colors come from the shared Context.SkyGradient — so
// it always produces exactly one marker entity, and the test confirms that marker
// round-trips and that the gradient-driven render is pixel-stable across seeds
// (covering midday, dusk, and twilight gradients).
func TestSkySceneListRoundTrip(t *testing.T) {
	const w, h = 480, 270
	seeds := []int64{42, 7, 256, 3, 100, 1024, 31337, 11, 2, 5, 8, 13}
	var sawSky bool

	for _, seed := range seeds {
		gen := skyTestContext(seed, w, h)
		list, err := (&Sky{}).Generate(gen)
		if err != nil {
			t.Fatalf("seed %d: generate: %v", seed, err)
		}

		data, err := MarshalSceneList(list)
		if err != nil {
			t.Fatalf("seed %d: marshal: %v", seed, err)
		}
		got, err := UnmarshalSceneList(data)
		if err != nil {
			t.Fatalf("seed %d: unmarshal: %v", seed, err)
		}
		data2, err := MarshalSceneList(got)
		if err != nil {
			t.Fatalf("seed %d: re-marshal: %v", seed, err)
		}
		if !bytes.Equal(data, data2) {
			t.Errorf("seed %d: scene list not stable across YAML round-trip\n--- first ---\n%s\n--- second ---\n%s", seed, data, data2)
		}

		// The reconstructed list must render identically to the original.
		if a, b := skyRenderListHash(t, seed, w, h, list), skyRenderListHash(t, seed, w, h, got); a != b {
			t.Errorf("seed %d: round-tripped scene list renders differently:\n got  %s\n want %s", seed, b, a)
		}

		for _, e := range list {
			if _, ok := e.(*SkyV0); !ok {
				t.Fatalf("seed %d: unexpected entity type %T", seed, e)
			}
			sawSky = true
		}
	}

	// Coverage sanity: every seed should produce exactly one sky marker entity.
	if !sawSky {
		t.Fatal("no sky entity generated across all seeds; the sky should always be present")
	}
}
