package scene

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"testing"

	"github.com/zostay/scifi-landscape/internal/canvas"
)

// waterTestContext builds the minimal Context a Water generator/renderer needs
// for a seed: the resolved ocean/land model and the scene geometry. It mirrors how
// Scene.Build wires these up — in particular it rebuilds the ocean global on its
// own derived "water" stream, exactly as Build does, so both generation and
// rendering see the identical shared global (the ocean is a scene-wide global,
// not generated by the element). Water draws no randomness of its own, so no
// element stream is needed; RenderList reflects already-drawn pixels off the
// (blank) canvas, which both renders share identically.
func waterTestContext(seed int64, w, h int) *Context {
	settings := NewSettings(seed, "", h)
	oc := buildOcean(deriveRng(seed, "water"), settings, h)
	return &Context{
		Ctx:      WithInstant(context.Background()),
		Canvas:   canvas.New(w, h),
		Settings: settings,
		Seed:     seed,
		W:        w,
		H:        h,
		Ocean:    oc,
		LandAt:   oc.LandAt,
		Rng:      deriveRng(seed, "water"),
	}
}

// waterRenderListHash renders a water scene list onto a fresh canvas and hashes
// the pixels. RenderList consumes no randomness, so the stream in the context is
// irrelevant here.
func waterRenderListHash(t *testing.T, seed int64, w, h int, list SceneList) string {
	t.Helper()
	c := waterTestContext(seed, w, h)
	if err := (&Water{}).RenderList(c, list); err != nil {
		t.Fatalf("seed %d: render list: %v", seed, err)
	}
	buf := make([]byte, w*h*4)
	c.Canvas.Snapshot(buf)
	sum := sha256.Sum256(buf)
	return hex.EncodeToString(sum[:])
}

// TestWaterSceneListRoundTrip mirrors TestPlanetsSceneListRoundTrip: a generated
// water scene list, serialized to YAML and read back, must (a) re-serialize to the
// same bytes and (b) render to the same pixels. This proves the "config +
// scene-list → render" reproducibility path for the ocean. Seeds without an ocean
// generate an empty list (still a valid round-trip with matching pixels).
func TestWaterSceneListRoundTrip(t *testing.T) {
	const w, h = 480, 270
	seeds := []int64{42, 7, 256, 3, 100, 1024, 31337, 11, 2, 5, 8, 13}
	var sawOcean, sawEmpty bool

	for _, seed := range seeds {
		gen := waterTestContext(seed, w, h)
		list, err := (&Water{}).Generate(gen)
		if err != nil {
			t.Fatalf("seed %d: generate: %v", seed, err)
		}

		data, err := MarshalSceneList(list)
		if err != nil {
			t.Fatalf("seed %d: marshal: %v", seed, err)
		}
		got, err := UnmarshalSceneList(data)
		if err != nil {
			t.Fatalf("seed %d: unmarshal: %v", seed, err)
		}
		data2, err := MarshalSceneList(got)
		if err != nil {
			t.Fatalf("seed %d: re-marshal: %v", seed, err)
		}
		if !bytes.Equal(data, data2) {
			t.Errorf("seed %d: scene list not stable across YAML round-trip\n--- first ---\n%s\n--- second ---\n%s", seed, data, data2)
		}

		// The reconstructed list must render identically to the original.
		if a, b := waterRenderListHash(t, seed, w, h, list), waterRenderListHash(t, seed, w, h, got); a != b {
			t.Errorf("seed %d: round-tripped scene list renders differently:\n got  %s\n want %s", seed, b, a)
		}

		switch len(list) {
		case 0:
			sawEmpty = true
		case 1:
			sawOcean = true
			if _, ok := list[0].(*WaterV0); !ok {
				t.Fatalf("seed %d: unexpected entity type %T", seed, list[0])
			}
		default:
			t.Fatalf("seed %d: water generated %d entities, want at most 1", seed, len(list))
		}
	}

	// Coverage sanity: the chosen seeds should exercise both an ocean scene (the
	// WaterV0 entity round-trips) and a no-ocean scene (the empty-list path).
	if !sawOcean {
		t.Error("no ocean generated across all seeds; pick seeds that produce water")
	}
	if !sawEmpty {
		t.Log("note: no oceanless scene in the seed set (empty-list path not exercised)")
	}
}
